version: '3.8'

services:
  test-db:
    image: postgres:15
    container_name: test_task_manager_db
    environment:
      POSTGRES_DB: test_task_manager
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - "5433:5432"  # Используем другой порт, чтобы не конфликтовать с основной БД
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d test_task_manager"]
      interval: 5s
      timeout: 5s
      retries: 5
